from flask import Flask

__all__ = ['app_cli_runner', 'check_output', 'click_echo', 'click_exit', 'conda_command', 'conda_executable', 'init_conda', 'platform_uname', 'run_command', 'run_subprocess']

def platform_uname(entry_python: str) -> str: ...
def click_echo(message: str, err: bool = False, fg: str | None = None): ...
def click_exit(message: str, return_code: int = 1): ...
def app_cli_runner(app: Flask, *args): ...
def run_command(*args: str, echo: bool = True, executable: str | None = None) -> int: ...
def run_subprocess(*args: str, echo: bool = True, shell: bool = True, executable: str | None = None, detached: bool = False, priority: int | None = None) -> int: ...
def check_output(*args: str, cwd: str | None = None, executable: str | None = None, encoding: str = 'utf-8', echo: bool = True, shell: bool = True) -> list[str]: ...
def conda_executable(*args: str, entry_python: str) -> str: ...
def conda_command(*args: str, entry_python: str, shell: bool = True, echo: bool = True, detached: bool = False, priority: int | None = None) -> int: ...
def init_conda(entry_python: str, python_version: str, force: bool = False, requirements_txt: str | None = None) -> int: ...
