[tool.black]
line-length = 160
include = "(\\.pyi?|\\.ipynb)$"
extend-exclude = "build"

[tool.isort]
profile = "black"
multi_line_output = 9
line_length = 160
skip_glob = [".*"]

known_local_folder = ["xbcli"]

import_heading_localfolder = "Local Modules"

[tool.pytest.ini_options]
pythonpath = ["."]
