[tool.black]
line-length = 160
include = "(\\.pyi?|\\.ipynb)$"
extend-exclude = "build"

[tool.isort]
profile = "black"
multi_line_output = 9
line_length = 160
skip_glob = [".*"]

known_local_folder = ["xbcli"]

import_heading_localfolder = "Local Modules"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
exclude = ["build", "dist"]

# mypy per-module options:

[[tool.mypy.overrides]]
module = "xbproc.a2l.*"